### ISSUE TITLE
exported COCO json not contained `annotations`

### ISSUE THREAD

**Issue by chy168** [ryouchinsa/Rectlabel-support#50]
Hi,

I'm trying to use `rectlabel_create_coco_tf_record.py` to convert COCO to TFRecord.
Once I run the command, it tell me:

```
Traceback (most recent call last):
  File "/Users/tester/codes/Rectlabel-support/rectlabel_create_coco_tf_record.py", line 195, in <module>
    tf.app.run()
  File "/Users/tester/codes/tensorflow_workspace/lib/python3.6/site-packages/tensorflow/python/platform/app.py", line 125, in run
    _sys.exit(main(argv))
  File "/Users/tester/codes/Rectlabel-support/rectlabel_create_coco_tf_record.py", line 184, in main
    num_shards=1)
  File "/Users/tester/codes/Rectlabel-support/rectlabel_create_coco_tf_record.py", line 160, in _create_tf_record_from_coco_annotations
    annotations_list = annotations_index[image['id']]
KeyError: 1
```

When I trying to troubleshot for this error, I found the exported COCO json file not contained `annotations` as below:

```
...
  "annotations" : [

  ],
...
```

is that a expected behavior? 

please advice me if anything else i forget to configure in RectLabel?

Thank you, it a awesome tool! :)

**Comment by ryouchinsa** [comment]
This is an example of the COCO JSON file.

```
{
  "images" : [
    {
      "id" : 1,
      "file_name" : "24254273-139193623405038-6052858076942303232-n.jpg",
      "width" : 768,
      "height" : 960
    },
    {
      "id" : 2,
      "file_name" : "23824755-1504327896532372-9173641443758047232-n.jpg",
      "width" : 768,
      "height" : 960
    }
  ],
  "annotations" : [
    {
      "area" : 39297,
      "segmentation" : {
        "size" : [
          960,
          768
        ],
        "counts" : "Q_h98bg06O1O1O1O1O1N2O2N1O1O1O1N2O1O1O1O1O1N2O1O1O1O1N2O1O1O1O1O1N2O2N1O1O1O1N2O1O1O1O1O1N2O1O1O1O1N2O1O1O1O1O1N2O2N1O1O1O1N2O1O1O1O1O1N2O1O1O1O1N2O1O1O1O1O1O101O000001O00000000000000001O0001O00001O001O01O01O00001O001O01O01O00001O001O00010O00001O00001O0010O0001O00001O001O01O0001O01O1O1O1O2O0O1O1O2N1O100O0000000001O01O00000001O00000000001O00000000010O00000000001O0001O001O010O001O001O01O01O001O0010O01O001O0001O00000000001O0000001O1O1N2O1O1O2N1O1O1O1O1O2N1O1O1O1O1O2N1O1O1O1O1O1O000000O100000O10O1000000O1000000O100000000O1000000O1000000O100000000O0100000O1000000O100000000O1000000O1000000O100000000O1000O10O1000000O100000000O1000000O100O1O100O1O1O1O100O1O1O10O01O1O1O100O1O100000000000000000000000001O000000000000000O10000O2O0O10000O10000O100O10001N100O1001O00001O00000010O0001O00000106I7I6K6I7I7F9VOPR]3"
      },
      "iscrowd" : 0,
      "image_id" : 1,
      "bbox" : [
        388,
        416,
        162,
        398
      ],
      "category_id" : 2,
      "id" : 1
    },
    {
      "area" : 4430,
      "segmentation" : {
        "size" : [
          960,
          768
        ],
        "counts" : "SiXc05kg0l0TO0000O100000000O2O0000000000O1000000O2O000O1000000O1000000O0100000O10000O100O100O1O010O100O100O1O10000O01000O10000O10O1000O10000O10001O0O1000000O101O00000O10O1000O01000000O01000O101O001O1O001O1O001O1O2N1O2N2N2N1N3M3M6J7J5J`^b0"
      },
      "iscrowd" : 0,
      "image_id" : 2,
      "bbox" : [
        268,
        822,
        56,
        113
      ],
      "category_id" : 1,
      "id" : 3
    }
  ],
  "categories" : [
    {
      "name" : "bare feet",
      "id" : 1
    },
    {
      "name" : "socks",
      "id" : 2
    }
  ]
}
```

"categories" corresponds to the Objects table on the setting dialog.

![2018-09-02 4 36 48](https://user-images.githubusercontent.com/1954306/44949389-304ebb80-ae6b-11e8-929f-d3201f04984f.png)

Did you register every object name in your xml files onto the Objects table?
We skip label names which are not registered onto the Objects table.

**Comment by chy168** [comment]
Hi,

Thanks for your quick reply.

Yes, i did register label name in Objects table.
These register label also show in ``categories`.

![image](https://user-images.githubusercontent.com/424758/44951519-175cff00-ae99-11e8-9f2b-9fbabaad9c88.png)

```
"categories" : [
    {
      "name" : "ignore",
      "id" : 1
    },
    {
      "name" : "tu-lun-sticker",
      "id" : 2
    },
    {
      "name" : "tu-lun-obj",
      "id" : 3
    },
    {
      "name" : "back-home-skill-button",
      "id" : 4
    },
    {
      "name" : "healing-skill-button",
      "id" : 5
    },
    {
      "name" : "teleport-skill-button",
      "id" : 6
    },
    {
      "name" : "sticker",
      "id" : 7
    },
    {
      "name" : "doll",
      "id" : 8
    },
    {
      "name" : "skill-button",
      "id" : 9
    }
  ]
```

Thank you!

**Comment by chyzz** [comment]
Hi,

I found a clue might related to my problem.
My registered labels are not selected any `attribute`  for them. Is that a problem?

**Comment by chyzz** [comment]
Hi,

I found a clue might related to my problem.
My registered labels are not selected any attribute for them. Is that a problem?

**Comment by chy168** [comment]
Hi,

I found a clue might related to my problem.
My registered labels are not selected any attribute for them. Is that a problem?

**Comment by chy168** [comment]
Hi,

attached exported setting file

```
{
  "objects" : [
    {
      "hidden" : false,
      "aspect_ratio" : "",
      "name" : "ignore",
      "attributes" : [

      ],
      "color" : {
        "red" : 0,
        "green" : 1,
        "blue" : 1
      }
    },
    {
      "color" : {
        "red" : 0.9687855,
        "green" : 1,
        "blue" : 0.1726742
      },
      "aspect_ratio" : "",
      "name" : "tu-lun-sticker",
      "attributes" : [

      ],
      "hidden" : false
    },
    {
      "color" : {
        "red" : 1,
        "green" : 0.8373545,
        "blue" : 0.1585512
      },
      "aspect_ratio" : "",
      "name" : "tu-lun-obj",
      "attributes" : [

      ],
      "hidden" : false
    },
    {
      "color" : {
        "red" : 0,
        "green" : 1,
        "blue" : 1
      },
      "aspect_ratio" : "",
      "name" : "back-home-skill-button",
      "attributes" : [

      ],
      "hidden" : false
    },
    {
      "color" : {
        "red" : 0.2068712,
        "green" : 1,
        "blue" : 0.154178
      },
      "aspect_ratio" : "",
      "name" : "healing-skill-button",
      "attributes" : [

      ],
      "hidden" : false
    },
    {
      "color" : {
        "red" : 0.7944086,
        "green" : 0.4540808,
        "blue" : 1
      },
      "aspect_ratio" : "",
      "name" : "teleport-skill-button",
      "attributes" : [

      ],
      "hidden" : false
    },
    {
      "color" : {
        "red" : 0.3849185,
        "green" : 0.8470168,
        "blue" : 1
      },
      "aspect_ratio" : "",
      "name" : "sticker",
      "attributes" : [

      ],
      "hidden" : false
    },
    {
      "color" : {
        "red" : 0.3434749,
        "green" : 1,
        "blue" : 0.5889418
      },
      "aspect_ratio" : "",
      "name" : "doll",
      "attributes" : [
        "brand",
        "color",
        "doll-type",
        "side"
      ],
      "hidden" : false
    },
    {
      "color" : {
        "red" : 0,
        "green" : 1,
        "blue" : 1
      },
      "aspect_ratio" : "",
      "name" : "skill-button",
      "attributes" : [

      ],
      "hidden" : false
    }
  ],
  "attributes" : [
    {
      "name" : "color",
      "prefix" : "",
      "items" : [
        "",
        "black",
        "red",
        "white",
        "yellow"
      ]
    },
    {
      "name" : "brand",
      "prefix" : "",
      "items" : [
        "",
        "adidas",
        "converse",
        "nike",
        "vans"
      ]
    },
    {
      "name" : "side",
      "prefix" : "",
      "items" : [
        "",
        "right",
        "left"
      ]
    },
    {
      "name" : "doll-type",
      "prefix" : "",
      "items" : [
        "sticker",
        "doll"
      ]
    }
  ]
}
```

**Comment by chy168** [comment]
If use my config to test:

`Without annotations ` reproduce steps:
1. Use any kind of label/category except of `doll` to label image
2. Export COCO json
3. Get no annotation COCO json

`With annotations ` reproduce steps:
1.  Use `doll` label and other to label image
2. Export COCO json
3. Get ONLY `doll` category info in annotation of COCO json

hope this can help you investigate easier. thank you :)

**Comment by chy168** [comment]
UPDATE:

if I add attribute to the label (ex: `A label`) in setting, edit the original rect from `A` -> `B` -> `A`.
Then, export COCO json again, the annotation will show.

Is there any way to reapply/refresh/reload all labeled rect without swap (edit like A->B->A) every label again?

Thanks :)

**Comment by ryouchinsa** [comment]
Hi, 
Thanks for your trial and errors.

We could find that the label names with dash could not be processed correctly when you export COCO JSON and mask images.

We submitted the new update version 2.08.
When the new update is released, we will let you know.

```
{
  "images" : [
    {
      "id" : 1,
      "file_name" : "24254273-139193623405038-6052858076942303232-n.jpg",
      "width" : 768,
      "height" : 960
    },
    {
      "id" : 2,
      "file_name" : "23824755-1504327896532372-9173641443758047232-n.jpg",
      "width" : 768,
      "height" : 960
    }
  ],
  "annotations" : [
    {
      "area" : 39297,
      "segmentation" : {
        "size" : [
          960,
          768
        ],
        "counts" : "Q_h98bg06O1O1O1O1O1N2O2N1O1O1O1N2O1O1O1O1O1N2O1O1O1O1N2O1O1O1O1O1N2O2N1O1O1O1N2O1O1O1O1O1N2O1O1O1O1N2O1O1O1O1O1N2O2N1O1O1O1N2O1O1O1O1O1N2O1O1O1O1N2O1O1O1O1O1O101O000001O00000000000000001O0001O00001O001O01O01O00001O001O01O01O00001O001O00010O00001O00001O0010O0001O00001O001O01O0001O01O1O1O1O2O0O1O1O2N1O100O0000000001O01O00000001O00000000001O00000000010O00000000001O0001O001O010O001O001O01O01O001O0010O01O001O0001O00000000001O0000001O1O1N2O1O1O2N1O1O1O1O1O2N1O1O1O1O1O2N1O1O1O1O1O1O000000O100000O10O1000000O1000000O100000000O1000000O1000000O100000000O0100000O1000000O100000000O1000000O1000000O100000000O1000O10O1000000O100000000O1000000O100O1O100O1O1O1O100O1O1O10O01O1O1O100O1O100000000000000000000000001O000000000000000O10000O2O0O10000O10000O100O10001N100O1001O00001O00000010O0001O00000106I7I6K6I7I7F9VOPR]3"
      },
      "iscrowd" : 0,
      "image_id" : 1,
      "bbox" : [
        388,
        416,
        162,
        398
      ],
      "category_id" : 1,
      "id" : 1
    },
    {
      "area" : 4430,
      "segmentation" : {
        "size" : [
          960,
          768
        ],
        "counts" : "SiXc05kg0l0TO0000O100000000O2O0000000000O1000000O2O000O1000000O1000000O0100000O10000O100O100O1O010O100O100O1O10000O01000O10000O10O1000O10000O10001O0O1000000O101O00000O10O1000O01000000O01000O101O001O1O001O1O001O1O2N1O2N2N2N1N3M3M6J7J5J`^b0"
      },
      "iscrowd" : 0,
      "image_id" : 2,
      "bbox" : [
        268,
        822,
        56,
        113
      ],
      "category_id" : 2,
      "id" : 2
    }
  ],
  "categories" : [
    {
      "name" : "tu-lun-sticker",
      "id" : 1
    },
    {
      "name" : "teleport-skill-button",
      "id" : 2
    }
  ]
}
```

**Comment by chy168** [comment]
glad to hear that
Thanks for your great effort and quick fix! 👍

**Comment by ryouchinsa** [comment]
The new update version 2.08 was released.
